/**
 * @xjl-resources/dsh-plugin-liquid-glass — host half.
 *
 * This file is the whole host-side contract of a UI project package, and it is three statements long on
 * purpose:
 *
 *   1. `inject: ['uiProjectsHost']` — the first-paint service is provided by `dsh-ui-projects`, which owns
 *      the contract: the presence announcement, the marker attribute, the fragment tag, and "read the
 *      settings document at emit time". Declaring the dependency is what makes Cordis park this row until
 *      that service exists, rather than letting it push nothing and say nothing.
 *   2. listen for `webserver/index-inject`, which the host webserver emits once per index render.
 *   3. push the rows the service builds for this project — the index table is collected fresh every
 *      render, so a toggle is reflected by the next reload with nothing to invalidate.
 *
 * `PROJECT_ID` is the one value here that is not derived, and `scripts/build.mjs` asserts it against
 * `package.json` → `dsh.uiProject.id` (the same document the installer validates), so a rename cannot
 * leave the host half announcing a project the manifest does not declare.
 *
 * The stylesheet argument is what makes this package's first paint its own: `BOOT_CSS` is generated by
 * `scripts/build.mjs` from `src/host/boot.css`, which is derived — rule for rule, and checked in both
 * directions — from this package's own `tokens.css` and `glass.css`.
 */

import { BOOT_CSS } from './boot-css.js'

/** The project this package contributes. Checked against the manifest at build time. */
const PROJECT_ID = 'liquid-glass'

/** Cordis row metadata. */
export const name = 'ui-project-liquid-glass'

/** The first-paint service, from the framework package. */
export const inject = ['uiProjectsHost']

/**
 * @param {import('@deepseek-ai/cordis').Context} ctx
 */
export function apply(ctx) {
  ctx.on('webserver/index-inject', (table) => {
    table.push(...ctx.uiProjectsHost.bootRows(PROJECT_ID, BOOT_CSS))
  })
}
